name       : aria2
version    : 1.34.0
release    : 18
source     :
    - https://github.com/aria2/aria2/releases/download/release-1.34.0/aria2-1.34.0.tar.xz : 3a44a802631606e138a9e172a3e9f5bcbaac43ce2895c1d8e2b46f30487e77a3
license    : GPL-2.0-or-later
component  : network.download
summary    : aria2 is a lightweight multi-protocol & multi-source command-line download utility.
description: |
    aria2 is a lightweight multi-protocol & multi-source command-line download utility. It supports HTTP/HTTPS, FTP, SFTP, BitTorrent and Metalink. aria2 can be manipulated via built-in JSON-RPC and XML-RPC interfaces.
builddeps  :
    - pkgconfig(libssh2)
    - pkgconfig(sqlite3)
    - pkgconfig(libxml-2.0)
    - ca-certs
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
