name       : aria2
version    : 1.25.0
release    : 7
homepage   : http://aria2.sourceforge.net/
source     :
    - https://github.com/aria2/aria2/releases/download/release-1.25.0/aria2-1.25.0.tar.xz : ff89eb4c76cfc816a6f5abc7dfd416cc3f339e7d02c761f822fa965a18cf0d35
license    : GPL-2.0
summary    : aria2 is a lightweight multi-protocol & multi-source command-line download utility.
component  : network.download
description: |
    aria2 is a lightweight multi-protocol & multi-source command-line download utility. It supports HTTP/HTTPS, FTP, SFTP, BitTorrent and Metalink. aria2 can be manipulated via built-in JSON-RPC and XML-RPC interfaces.
builddeps  :
    - pkgconfig(libssh2)
    - pkgconfig(sqlite3)
    - pkgconfig(libxml-2.0)
    - ca-certs
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
