name       : aria2
version    : 1.30.0
release    : 12
homepage   : https://aria2.github.io/
source     :
    - https://github.com/aria2/aria2/releases/download/release-1.30.0/aria2-1.30.0.tar.xz : bf6c5366d11d2a6038c8e19f01f9b874041793aaf317e0206120e3e8c9c431f6
license    : GPL-2.0
summary    : aria2 is a lightweight multi-protocol & multi-source command-line download utility.
component  : network.download
description: |
    aria2 is a lightweight multi-protocol & multi-source command-line download utility. It supports HTTP/HTTPS, FTP, SFTP, BitTorrent and Metalink. aria2 can be manipulated via built-in JSON-RPC and XML-RPC interfaces.
builddeps  :
    - pkgconfig(libssh2)
    - pkgconfig(sqlite3)
    - pkgconfig(libxml-2.0)
    - ca-certs
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
