name       : aria2
version    : 1.32.0
release    : 14
source     :
    - https://github.com/aria2/aria2/releases/download/release-1.32.0/aria2-1.32.0.tar.xz : 546e9194a9135d665fce572cb93c88f30fb5601d113bfa19951107ced682dc50
license    : GPL-2.0
component  : network.download
summary    : aria2 is a lightweight multi-protocol & multi-source command-line download utility.
description: |
    aria2 is a lightweight multi-protocol & multi-source command-line download utility. It supports HTTP/HTTPS, FTP, SFTP, BitTorrent and Metalink. aria2 can be manipulated via built-in JSON-RPC and XML-RPC interfaces.
builddeps  :
    - pkgconfig(libssh2)
    - pkgconfig(sqlite3)
    - pkgconfig(libxml-2.0)
    - ca-certs
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
